### ISSUE TITLE
cytoscape v2.7.16 breaks tutorial 2

### ISSUE THREAD

**Issue by joker234** [cytoscape/cytoscape.js-blog#6]
The arrows in [Tutorial 2](http://blog.js.cytoscape.org/2016/06/08/glycolysis/) are not rendered if I'm using the current [release version of cytoscape.js](http://js.cytoscape.org/download/cytoscape.js-2.7.16.zip). If I'm using the cytoscape.js file provided with the [source files of the tutorial](https://github.com/cytoscape/cytoscape.js-blog/tree/gh-pages/public/demos/glycolysis) everything is fine. With the release version I only see bare lines between the nodes which are not looking quite nice (see attached image).
![screenshot_2017-04-01_19-34-32_ 0200](https://cloud.githubusercontent.com/assets/2878899/24580952/468613fe-1712-11e7-9aa6-b18a2412980b.jpg)

**Comment by maxkfranz** [comment]
@josephst Would you please look into this?
