### ISSUE TITLE
Tutorial Layout code doesn't work in current version

### ISSUE THREAD

**Issue by NickEngland** [cytoscape/cytoscape.js-blog#9]
https://github.com/cytoscape/cytoscape.js-blog/blob/gh-pages/_posts/2016-05-24-getting-started.md

The layout code is out of date, as now you need to run:

```
 var layout=cy.layout({
            name: 'circle'
        });
        layout.run();
```

To update the layout after adding the nodes in the tutorial.

**Comment by maxkfranz** [comment]
Updated.  Thanks
